### ISSUE TITLE
[Build logs]: Increase message streaming chunk size

### ISSUE THREAD

**Issue by Gerbuuun** [nuxt-hub/feedback#12]
**Is your feature request related to a problem? Please describe.**
When watching build logs, the streaming of log messages is limited by the chunk size. So you have to wait considerable amount of time for the messages to stream in even though the messages itself were sent a few milliseconds apart.

**Describe the solution you'd like**
Is it possible to increase the chunk size?

**Comment by farnabaz** [comment]
I didn't understand your point about the increasing chunk size. Build logs are streamed through a socket based on line numbers, so whenever a new line is logged in the build, there is a new message in the socket. I don't see how chunk size is applicable to it.

![Screenshot 2024-05-06 at 15.44.41.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2024_05_06_at_15_44_41_ae0719bf02.png)

**Comment by Gerbuuun** [comment]
I probably misunderstood then. But the thing is that during a build the logs print a few lines a second but in reality they were only tens of milliseconds apart. What I meant is: could you add all these into a single socket message so I don't have to wait for them to stream in? On the cloudflare dashboard they are instant

**Comment by Gerbuuun** [comment]
This is what I mean. The logs in the hub admin feels slow to me. It feels like I have to wait for the admin to finish.
I know this is based on feelings but we all like a snappy experience right?

https://github.com/nuxt-hub/feedback/assets/12988935/4349eb6c-7df6-406b-b159-cfe907ff01a4

**Comment by farnabaz** [comment]
I see, I'm not sure wether we can improve this behaviour or not, as I checked seems that socket messages slightly delayed in NuxtHub. This is strange, since NuxtHub uses the same socket as Cloudflare does. You see the difference in the devtools messages
Checkout first 6 seconds:
http://volta.s3.fr-par.scw.cloud/Clean_Shot_2024_05_07_at_11_55_47_2c4b7b228f.mp4
