### ISSUE TITLE
Add the Cloudflare plan need to template (Atinotes fails with free tier)

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-hub/feedback#13]
**Is your feature request related to a problem? Please describe.**

I was trying to deploy the template `atinotes` to Cloudflare from the page `New Project > Clone a Template`. Unfortunately, this template use the Nuxt Content module which create a bundle size of 2.7mb (gzipped) which is more than the 1mb allowed by the free plan.

This template is a really good use case of NuxtHub KV but not everyone will be able to deploy it. Could be possible to add a tag `Cloudflare Free` and `Cloudflare Pro` to tell to people if they can use or not the template. 

(Maybe you can know the Cloudflare tier using the token which could conditionally shows a hint 'A Pro Cloudflare Plan is need for this deployment because ...')

**Comment by Atinux** [comment]
Thank you for your feedback @Barbapapazes 

I've updated the templates page to give more hints about it: https://twitter.com/nuxt_hub/status/1786370269184958482
