### ISSUE TITLE
Migration with raw SQL does not works

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt-hub/feedback#15]
**Describe the bug**

I'm trying to run migration in dev using this recipe, https://hub.nuxt.com/docs/recipes/hooks, but it does not works.

**To Reproduce**

https://github.com/Barbapapazes/nuxt-hub-raw-sql

**Expected behavior**

I did not expect the error but a working migration step, like when I use Drizzle where everything works fine.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WSL2 with Ubuntu

**Dependencies:**
    "@nuxthub/core": "^0.5.14",
    "nuxt": "^3.11.2",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"

**Dev Dependencies:**
    "wrangler": "^3.53.0"

**Comment by Atinux** [comment]
What is the error your are receiving @Barbapapazes ?

**Comment by Barbapapazes** [comment]
> What is the error your are receiving @Barbapapazes ?

This one

```
ERROR  [nitro] [unhandledRejection] D1_EXEC_ERROR: Error in line 1: CREATE TABLE IF NOT EXISTS todos (: incomplete input

at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at <anonymous> (server/plugins/migrations.ts:5:1)
at async Promise.all (index 0)
at <anonymous> (node_modules/.pnpm/@nuxthub+core@0.5.14_ioredis@5.4.1_nuxt@3.11.2_@parcel+watcher@2.4.1_@types+node@20.12.7_@uno_v6ufku3kw6jhvrpovvvt7rg5kq/node_modules/@nuxthub/core/dist/runtime/ready.dev.mjs:5:3)
```

**Comment by Atinux** [comment]
I think it's because you cannot use `\n` inside the query.

Could you try with removing the `\n` in your SQL statement? If so, we should add a `.replace(/\n/g, '')` to the end of the statement.

**Comment by Barbapapazes** [comment]
> I think it's because you cannot use `\n` inside the query.
> 
> Could you try with removing the `\n` in your SQL statement? If so, we should add a `.replace(/\n/g, '')` to the end of the statement.

It works now!
