### ISSUE TITLE
Option to add env vars when deploying from a github repo

### ISSUE THREAD

**Issue by fayazara** [nuxt-hub/feedback#2]
Description:

My project has a build time dependency of `nuxt/ui-pro`, it would be nice to have environment variables supported right in this modal, when deploying a project from github repo option

![Screenshot 30-03 at 13](https://github.com/nuxt-hub/feedback/assets/15716057/86bcdb6c-04ed-431b-b65a-d217198f091a)

**Comment by Atinux** [comment]
It's planned and will be implemented very soon!

**Comment by Atinux** [comment]
This is now possible @fayazara 

![CleanShot 2024-04-08 at 13.42.39@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2024_04_08_at_13_42_39_2x_2f84eaa882.png)
