### ISSUE TITLE
Ability to switch between projects from sidebar

### ISSUE THREAD

**Issue by IsraelOrtuno** [nuxt-hub/feedback#5]
**Is your feature request related to a problem? Please describe.**
Would be so nice if you could switch between projects from the sidebar itself. 

**Describe the solution you'd like**
Maybe turning the project name into a dropdown just like happens at the project homepage with the teams.

<img width="247" alt="image" src="https://github.com/nuxt-hub/feedback/assets/1769417/413f66b1-d904-4be0-b6c6-97dafbdd80bf">
<img width="389" alt="image" src="https://github.com/nuxt-hub/feedback/assets/1769417/456c1e01-69a5-4d61-8504-1789cf2a1eaa">

**Comment by Atinux** [comment]
It's live!

https://twitter.com/Atinux/status/1778075917442560114
